openapi: 3.0.3
info:
  title: Book Orders API
  description: API for managing book orders.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/orders:
    get:
      summary: Get all orders
      operationId: getOrders
      tags: [Orders]
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Create a new order
      operationId: createOrder
      tags: [Orders]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Created order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        customerName:
          type: string
        bookTitle:
          type: string
        quantity:
          type: integer
        status:
          type: string
